name: Build (Release)

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build-release:
    uses: ./.github/workflows/build.yml
    with:
      base_image: docker.io/library/fedora:36
      image_name: samba
      platforms: linux/amd64,linux/arm64
      release: true
    secrets:
      username: ${{ github.actor }}
      token: ${{ secrets.GITHUB_TOKEN }}
