name: Build (Edge)

on:
  push:
    branches: [ dev ]

jobs:
  build-release:
    uses: ./.github/workflows/build.yml
    with:
      base_image: docker.io/library/fedora:36
      image_name: samba
      platforms: linux/amd64
      release: false
    secrets:
      username: ${{ github.actor }}
      token: ${{ secrets.GITHUB_TOKEN }}
